Repository TEAM-TATTOUR/tattour-client, pull requests merged in 2024-02, with the labels that each got.

#588 [SP1] api 누락된 항목 반영
  src/components/MyTattoo/MyLike.tsx
  src/libs/hooks/detail/useGetSticker.tsx
  src/libs/hooks/useGetCustomDetail.ts
  src/libs/hooks/useGetLikeSticker.ts
  src/libs/hooks/useKakaoLogin.tsx
  src/page/DetailPage.tsx
Labels: 🐞 BugFix, 📬 API

#593 [Hotfix] 상세페이지 mainImage 연결
  src/assets/video/tattour_loading.json
  src/components/Detail/DetailCarousel.tsx
  src/page/DetailPage.tsx
  src/page/LoadingPage.tsx
Labels: 🐞 BugFix

#599 [ hotfix ] 로컬스토리지 -> 세션스토리지로 변경
  src/libs/api.ts
Labels: 🔨 Refactor

#601 [S1] 프로그래스 바 진행도 관련 이슈 해결
  src/page/Login/LoginPage.tsx
Labels: 🔨 Refactor, 💌 Login

#594 [ListPage]🍝코드 정리
  src/components/List/FilterBottom.tsx
  src/components/List/FilterButton.tsx
  src/components/List/FilterSheet.tsx
  src/components/List/TattooCard.tsx
  src/components/List/TattooList.tsx
  src/constants/ListInfo.ts
  src/libs/hooks/list/useGetAllList.tsx
  src/page/ListPage.tsx
  src/styles/GlobalStyle.ts
Labels: 🔨 Refactor, 📑 List

#595 feature/OP => develop
  src/common/SmallTattooCard.tsx
  src/components/Custom/Common/OnBoardingFooter.tsx
  src/components/Custom/Common/Receipt/ReceiptDetail.tsx
  src/components/Custom/Common/Receipt/ReceiptFooter.tsx
  src/components/Custom/Common/Receipt/ReceiptLayout.tsx
  src/components/Custom/Common/Size/CustomSelectSize.tsx
  src/components/Custom/HaveDesign/Reference/CustomReference.tsx
  src/components/Custom/NoDesign/Img/CustomImgLayout.tsx
  src/components/Custom/NoDesign/NoDesignFooter.tsx
  src/components/Custom/PriceFooter.tsx
  src/components/MyTattoo/MyLike.tsx
  src/components/Register/RegisterName.tsx
  src/constants/TitleInfo.ts
  src/page/DetailPage.tsx
Labels: 🌱 Merge

#611 [SP1] 커스텀 팔레트 정렬 수정, UX 라이팅 수정, 화면 사이즈 변경에 따른 canvas 사이즈 조정 함수 추가
  src/components/Custom/HaveDesign/Reference/Canvas.tsx
  src/components/Custom/HaveDesign/Reference/ColorPicker.tsx
  src/components/Custom/HaveDesign/Reference/CustomImageAttach.tsx
  src/components/Custom/HaveDesign/Reference/CustomReference.tsx
  src/components/Custom/HaveDesign/Reference/PaintBottomHeader.tsx
  src/components/Custom/HaveDesign/Reference/PaintBottomSheet.tsx
Labels: 🔨 Refactor, ✏️ Custom

#616 [S1] 로그인 관련 예외 처리
  src/Router.tsx
  src/common/SideMenu.tsx
  src/components/Detail/DetailFooter.tsx
  src/libs/hooks/Interceptors.tsx
Labels: 🐞 BugFix, 👨‍👩‍👧‍👦 Common, 📬 API

#617 [S1] 공통 BottomSheet 적용
  src/common/BottomSheet.tsx
  src/components/Custom/Common/Select/SelectCustomPolicyBottom.tsx
  src/components/Custom/HaveDesign/Reference/PaintBottomSheet.tsx
  src/components/Custom/PublicBottomSheet.tsx
  src/components/Detail/DetailBottom.tsx
  src/components/List/FilterSheet.tsx
  src/components/Order/RefundBottom.tsx
  src/styles/GlobalStyle.ts
Labels: 👨‍👩‍👧‍👦 Common, 🔨 Refactor

#615 [S1/Custom] CustomApply Post haveDesign 값 전달 방식 수정 / haveDesign 플래그 값 변동
  src/Router.tsx
  src/components/Custom/Common/Select/SelectCustom.tsx
  src/components/Custom/Common/Select/SelectCustomFooter.tsx
  src/libs/hooks/usePostCustomApply.ts
  src/page/Custom/Common/CommonCustomPage.tsx
  src/page/Custom/HaveDesign/HaveDesignCustomPage.tsx
  src/page/Custom/NoDesign/NoDesignCustomPage.tsx
Labels: 🔨 Refactor

#622 [S1] 인증번호 요청 버튼 클릭 시, n초 간 버튼 비활성화
  src/components/Register/RegisterPhoneNumForm.tsx
Labels: 🔨 Refactor, 💌 Login

#623 Refactor/#596 order page
  src/components/Detail/DetailFooter.tsx
  src/components/Order/DeliveryInfo.tsx
  src/components/Order/OrderFooter.tsx
  src/components/Order/ProductInfo.tsx
  src/libs/hooks/detail/usePostCart.ts
  src/libs/hooks/detail/usePostLiked.ts
  src/page/LoadingPage.tsx
  src/page/Order/OrderPage.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#626 [S1] 상세페이지 뒤로가기 위치 변경
  src/page/DetailPage.tsx
Labels: 🐞 BugFix
